### PR TITLE
[FIX] DecoyDatabase detects already decoy'd DBs

### LINKED ISSUE #4917: DecoyDatabase should detect already decoy'd DBs
our example FASTA files in `share` sometimes contain outdated Decoy symbols (e.g. `_rev` as suffix).
If one is not careful, this can lead to subtle errors which are a bit tricky to find when a downstream tool crashes.

At least our DecoyDatabase tool should check if its consuming a decoy'ed DB (the above example is currently happily reversed **again**).

This is already mentioned in  #4662, but I think its very important to fix and to prevent accidental errors with high potential for frustration.

### PR DESCRIPTION
**Pull request by hbeschorner**
# Description

Added check, so DecoyDatabase will terminate if input data is already decoy’d.
Also added tests for the function.

Fixes #4917

# Checklist:
- [x] Make sure that you are listed in the AUTHORS file
- [x] Add relevant changes and new features to the CHANGELOG file
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes
- [x] Updated or added python bindings for changed or new classes. (Tick if no updates were necessary.)

# How can I get additional information on failed tests during CI:
If your PR is failing you can check out 
- http://cdash.openms.de/index.php?project=OpenMS and look for your PR. If you click in the column that lists the failed tests you will get detailed error messages.
- Or click on the action: e.g., for clang-format linting

# Note:
- Once you opened a PR try to minimize the number of *pushes* to it as every push will trigger CI (automated builds and test) and is rather heavy on our infrastructure (e.g., if several pushes per day are performed).

# Advanced commands (admins / reviewer only):
- `/rebase` will try to rebase the PR on the current develop branch.
- `/reformat` (experimental) applies the clang-format style changes as additional commit
- setting the label "NoJenkins" will skip tests for this PR on jenkins (saves resources e.g., on edits that do not affect tests)
- commenting with `rebuild jenkins` will retrigger Jenkins-based CI builds

### CODE REVIEW

**Comment by hbeschorner** [comment]
Was hat es mit den ganzen commits auf sich die nicht von mir sind, sind die einfach von Änderungen in OpenMS die bei mir aber noch nicht hier gemerged wurden?

**Comment by cbielow** [comment]
> Was hat es mit den ganzen commits auf sich die nicht von mir sind, sind die einfach von Änderungen in OpenMS die bei mir aber noch nicht hier gemerged wurden?

Genau. Das sollte jetzt gefixt sein.

File: src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h [hunk 1]
```diff
@@ -350,6 +350,15 @@ class DecoyHelper
...
+  {
+    std::unordered_map<std::string, std::pair<Size, Size>> decoy_count; ///< map decoys to counts of occurrences as prefix/suffix
+    std::unordered_map<std::string, std::string> decoy_case_sensitive; ///< map case insensitive strings back to original case (as used in fasta)
+    Size all_prefix_occur; ///< number of proteins with found decoy_prefix
+    Size all_suffix_occur; ///< number of proteins with found decoy_suffix
+    Size all_proteins_count; ///< number of all checked proteins
+  };
+
   // decoy strings
   inline static const std::vector<std::string> affixes = { "decoy", "dec", "reverse", "rev", "reversed", "__id_decoy", "xxx", "shuffled", "shuffle", "pseudo", "random" };
```
Comment (morm24) [inline src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h]: Does this need to be a Vector? You only have to read the strings and do not mutate them. So maybe a constant string array would be more performance oriented. 
```suggestion
  inline static const std::string[11] affixes = { "decoy", "dec", "reverse", "rev", "reversed", "__id_decoy", "xxx", "shuffled", "shuffle", "pseudo", "random" };
```

File: src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h [hunk 2]
```diff
@@ -366,6 +375,82 @@ class DecoyHelper
   */
   template<typename T>
   static Result findDecoyString(FASTAContainer<T>& proteins)
+  {
+    // calls function to search for decoys in input data
+    DecoyData decoy_info = countDecoys(proteins);
+
+    // DEBUG ONLY: print counts of found decoys
+      for (auto &a : decoy_info.decoy_count)
```
Comment (lennykovac) [inline src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h]: for (const auto & a....) We need only read-access.

File: src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h [hunk 3]
```diff
@@ -366,6 +375,82 @@ class DecoyHelper
...
+
+    // Decoy suffix occurred at least 80% of all suffixes + observed in at least 40% of all proteins -> set it as suffix decoy
+    for (const auto& pair : decoy_info.decoy_count)
+    {
+      const std::string& case_insensitive_decoy_string = pair.first;
+      const std::pair<Size, Size>& prefix_suffix_counts = pair.second;
+      double freq_suffix = static_cast<double>(prefix_suffix_counts.second) / static_cast<double>(decoy_info.all_suffix_occur);
+      double freq_suffix_in_proteins = static_cast<double>(prefix_suffix_counts.second) / static_cast<double>(decoy_info.all_proteins_count);
+
+      if (freq_suffix >= 0.8 && freq_suffix_in_proteins >= 0.4)
```
Comment (lennykovac) [inline src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h:449]: I dont know which one is more likley **not** to occure.... But that could be moved to the front of the expression.

File: src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h [hunk 4]
```diff
@@ -366,6 +375,82 @@ class DecoyHelper
...
+    if (decoy_info.all_prefix_occur == decoy_info.all_suffix_occur)
+    {
+      OPENMS_LOG_ERROR << "Unable to determine decoy string (prefix and suffix occur equally often)!" << std::endl;
+      return {false, "?", true};
+    }
+
+    // Decoy prefix occurred at least 80% of all prefixes + observed in at least 40% of all proteins -> set it as prefix decoy
+    for (const auto& pair : decoy_info.decoy_count)
+    {
+      const std::string & case_insensitive_decoy_string = pair.first;
```
Comment (lennykovac) [inline src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h:424]: Do we really have to allocate here? Cant we just return pair.first in line 418?

File: src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h [hunk 5]
```diff
@@ -366,6 +375,82 @@ class DecoyHelper
...
+      const std::pair<Size, Size>& prefix_suffix_counts = pair.second;
+      double freq_prefix = static_cast<double>(prefix_suffix_counts.first) / static_cast<double>(decoy_info.all_prefix_occur);
+      double freq_prefix_in_proteins = static_cast<double>(prefix_suffix_counts.first) / static_cast<double>(decoy_info.all_proteins_count);
+
+      if (freq_prefix >= 0.8 && freq_prefix_in_proteins >= 0.4)
```
Comment (lennykovac) [inline src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h:429]: I dont know which one is more likley **not** to occure.... But that could be moved to the front of the expression.

File: src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h [hunk 6]
```diff
@@ -366,6 +375,82 @@ class DecoyHelper
...
+        }
+
+        return { true, decoy_info.decoy_case_sensitive[case_insensitive_decoy_string], true};
+      }
+    }
+
+    // Decoy suffix occurred at least 80% of all suffixes + observed in at least 40% of all proteins -> set it as suffix decoy
+    for (const auto& pair : decoy_info.decoy_count)
+    {
+      const std::string& case_insensitive_decoy_string = pair.first;
```
Comment (lennykovac) [inline src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h:444]: Allocataion really necassary??

File: src/utils/DecoyDatabase.cpp [hunk 7]
```diff
@@ -201,8 +204,64 @@ class TOPPDecoyDatabase :
     Math::RandomShuffler shuffler(seed);
     for (Size i = 0; i < in.size(); ++i)
     {
-      f.readStart(in[i]);
+      // check if decoy_string is common decoy string (e.g. decoy, rev, ...)
+      try
+      {
+        String decoy_string_lower = decoy_string;
+        decoy_string_lower.toLower();
+        bool is_common = 0;
```
Comment (lennykovac) [inline src/utils/DecoyDatabase.cpp]: I always think bool x = 0 evaluates to false. Would be better to read if we init it with : True

Comment (lennykovac) [reply src/utils/DecoyDatabase.cpp]: const auto & ?

File: src/utils/DecoyDatabase.cpp [hunk 8]
```diff
@@ -201,8 +204,64 @@ class TOPPDecoyDatabase :
...
+        OPENMS_LOG_FATAL_ERROR << "DecoyDatabase failed due to: " << e.what() << '\n';
+        return INCOMPATIBLE_INPUT_DATA;
+      }
 
+      // check input files for decoys
+      try
+      {
+        std::vector<FASTAFile::FASTAEntry> data;
+        f.load(in[i], data);
+        FASTAContainer<TFI_Vector> in_entries = data;
```
Comment (lennykovac) [inline src/utils/DecoyDatabase.cpp]: FASTAContainer<TFI_Vector> in_entries = std::move(data)

File: src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h (hunk 1 above)
Comment (lennykovac) [reply src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h]: > Does this need to be a Vector? You only have to read the strings and do not mutate them. So maybe a constant string array would be more performance oriented.

Isnt the object sitting on the stack anyways?

File: src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h [hunk 9]
```diff
@@ -350,6 +350,15 @@ class DecoyHelper
     bool is_prefix; ///< on success, was it a prefix or suffix
   };
 
+  struct DecoyData
```
Comment (cbielow) [inline src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h]: `DecoyStatistics`

File: src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h [hunk 10]
```diff
@@ -366,6 +375,82 @@ class DecoyHelper
...
+
+    OPENMS_LOG_ERROR << "Unable to determine decoy string and its position. Please provide a decoy string and its position as parameters." << std::endl;
+    return {false, "?", true};
+  }
+
+  /**
+  @brief Function to count the occurrences of decoy strings in a given set of protein names
+
+  Tested decoy strings are "decoy", "dec", "reverse", "rev", "__id_decoy", "xxx", "shuffled", "shuffle", "pseudo" and "random".
+  Returns all data needed for interpretation (see DecoyHelper::DecoyCounts).
```
Comment (cbielow) [inline src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h]: DecoyStatistics

File: src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h [hunk 11]
```diff
@@ -366,6 +375,82 @@ class DecoyHelper
...
+    }
+
+    OPENMS_LOG_ERROR << "Unable to determine decoy string and its position. Please provide a decoy string and its position as parameters." << std::endl;
+    return {false, "?", true};
+  }
+
+  /**
+  @brief Function to count the occurrences of decoy strings in a given set of protein names
+
+  Tested decoy strings are "decoy", "dec", "reverse", "rev", "__id_decoy", "xxx", "shuffled", "shuffle", "pseudo" and "random".
```
Comment (cbielow) [inline src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h]: Tip: reference static vector/array

File: src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h [hunk 12]
```diff
@@ -366,6 +375,82 @@ class DecoyHelper
...
+  Returns all data needed for interpretation (see DecoyHelper::DecoyCounts).
+  */
+  template<typename T>
+  static DecoyData countDecoys(FASTAContainer<T>& proteins)//, const std::string decoy_string_custom)
```
Comment (cbielow) [inline src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h]: const?

File: src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h [hunk 13]
```diff
@@ -366,6 +375,82 @@ class DecoyHelper
...
   {
     // common decoy strings in FASTA files
     // note: decoy prefixes/suffices must be provided in lower case
```
Comment (cbielow) [inline src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h:475]: Instanciate `DecoyStatistics` here.
Return it at the end

File: src/tests/topp/CMakeLists.txt [hunk 14]
```diff
@@ -2815,15 +2815,19 @@ set_tests_properties("UTILS_DatabaseFilter_4_out" PROPERTIES DEPENDS "UTILS_Data
...
 add_test("UTILS_DecoyDatabase_3_out" ${DIFF} -in1 DecoyDatabase_3.fasta.tmp -in2 ${DATA_DIR_TOPP}/DecoyDatabase_3_out.fasta )
 set_tests_properties("UTILS_DecoyDatabase_3_out" PROPERTIES DEPENDS "UTILS_DecoyDatabase_3")
-add_test("UTILS_DecoyDatabase_4" ${TOPP_BIN_PATH}/DecoyDatabase -test -type RNA -in ${DATA_DIR_TOPP}/DecoyDatabase_4.fasta -out DecoyDatabase_4.fasta.tmp -decoy_string "blabla" -decoy_string_position "prefix" -method reverse -seed 42 )
+add_test("UTILS_DecoyDatabase_4" ${TOPP_BIN_PATH}/DecoyDatabase -test -type RNA -in ${DATA_DIR_TOPP}/DecoyDatabase_4.fasta -out DecoyDatabase_4.fasta.tmp -decoy_string "DECOY_SEQ_" -decoy_string_position "prefix" -method reverse -seed 42 )
 add_test("UTILS_DecoyDatabase_4_out" ${DIFF} -in1 DecoyDatabase_4.fasta.tmp -in2 ${DATA_DIR_TOPP}/DecoyDatabase_4_out.fasta )
 set_tests_properties("UTILS_DecoyDatabase_4_out" PROPERTIES DEPENDS "UTILS_DecoyDatabase_4")
+add_test("UTILS_DecoyDatabase_5" ${TOPP_BIN_PATH}/DecoyDatabase -test -in ${DATA_DIR_TOPP}/DecoyDatabase_5.fasta -out DecoyDatabase_5.fasta.tmp)
```
Comment (cbielow) [inline src/tests/topp/CMakeLists.txt:2828]: add comment why it is expected to fail

File: src/utils/DecoyDatabase.cpp [hunk 15]
```diff
@@ -71,6 +72,8 @@ using namespace std;
 
   The tool will keep track of all protein identifiers and report duplicates.
 
+  Also the tool automatically checks for decoys already in the input files (based on most common pre-/suffixes).
```
Comment (cbielow) [inline src/utils/DecoyDatabase.cpp]: and what happens if 'true`?

File: src/utils/DecoyDatabase.cpp (hunk 7 above)
Comment (cbielow) [reply src/utils/DecoyDatabase.cpp]: ` = false`
`is_common{false};`

File: src/utils/DecoyDatabase.cpp [hunk 16]
```diff
@@ -201,8 +204,64 @@ class TOPPDecoyDatabase :
...
     for (Size i = 0; i < in.size(); ++i)
     {
-      f.readStart(in[i]);
+      // check if decoy_string is common decoy string (e.g. decoy, rev, ...)
+      try
+      {
+        String decoy_string_lower = decoy_string;
+        decoy_string_lower.toLower();
+        bool is_common = 0;
+        for (auto a :  DecoyHelper::affixes){
```
Comment (cbielow) [inline src/utils/DecoyDatabase.cpp]: const auto&

Comment (cbielow) [reply src/utils/DecoyDatabase.cpp]: `{`

File: src/utils/DecoyDatabase.cpp [hunk 17]
```diff
@@ -201,8 +204,64 @@ class TOPPDecoyDatabase :
...
+          if((decoy_string_lower.hasPrefix(a) && decoy_string_position_prefix) || (decoy_string_lower.hasSuffix(a) && !decoy_string_position_prefix))
+          {
+            is_common = 1;
```
Comment (cbielow) [inline src/utils/DecoyDatabase.cpp]: true

File: src/utils/DecoyDatabase.cpp (hunk 7 above)
Comment (cbielow) [inline src/utils/DecoyDatabase.cpp]: move into separate function.
Call function once BEFORE the loop

File: src/utils/DecoyDatabase.cpp [hunk 18]
```diff
@@ -201,8 +204,64 @@ class TOPPDecoyDatabase :
...
+            "Given decoy string is not allowed. Please use one of the following strings as either prefix or suffix (case insensitive): \n"
+            "decoy, dec, reverse, rev, reversed, __id_decoy, xxx, shuffled, shuffle, pseudo, random"
+          );
+        }
+      }
+      catch(OpenMS::Exception::IllegalArgument& e)
+      {
+        // if decoy_string is not one of the allowed decoy strings, program terminates with exit code 11
+        OPENMS_LOG_FATAL_ERROR << "DecoyDatabase failed due to: " << e.what() << '\n';
+        return INCOMPATIBLE_INPUT_DATA;
```
Comment (cbielow) [inline src/utils/DecoyDatabase.cpp]: either use `return` right away OR throw exception which terminates the program

File: src/utils/DecoyDatabase.cpp [hunk 19]
```diff
@@ -201,8 +204,64 @@ class TOPPDecoyDatabase :
...
+      try
+      {
+        std::vector<FASTAFile::FASTAEntry> data;
+        f.load(in[i], data);
+        FASTAContainer<TFI_Vector> in_entries = data;
+        auto r = DecoyHelper::countDecoys(in_entries);
+        // if decoys found, throw exception
+        if (static_cast<double>(r.all_prefix_occur + r.all_suffix_occur) >= 0.4 * static_cast<double>(r.all_proteins_count))
+      {
+        throw OpenMS::Exception::InvalidInput(
```
Comment (cbielow) [inline src/utils/DecoyDatabase.cpp]: return immediately

File: src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h (hunk 12 above)
Comment (vrossow) [reply src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h]: Can't be const because member variables (active (forefront) data) in FASTAContainer are changed, the FASTA files or vector<FASTAEntries> that are given to the constructor of FASTAContainer are already const.

File: src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h (hunk 1 above)
Comment (hbeschorner) [reply src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h]: Has to be a vector because the following function (ListUtils::concatenate) working with affixes needs a vector as input.

File: src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h [hunk 20]
```diff
@@ -360,141 +372,153 @@ class DecoyHelper
...
+
+  /**
+  @brief Function to count the occurrences of decoy strings in a given set of protein names
+
+  For tested decoy strings see DecoyHelper::affixes.
+  Returns all data needed for interpretation (see DecoyHelper::DecoyStatistics).
+  */
+  template<typename T>
+  static DecoyStatistics countDecoys(FASTAContainer<T>& proteins)
+  {
```
Comment (vrossow) [inline src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h:473]: Can not be const because member variables (active (forefront) data) in FASTAContainer are changed, the FASTA files or vector that are given to the constructor of FASTAContainer are already const.

File: src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h [hunk 21]
```diff
@@ -360,141 +372,153 @@ class DecoyHelper
...
+    // common decoy strings in FASTA files
+    // note: decoy prefixes/suffices must be provided in lower case
+
+    DecoyStatistics ds;
+    ds.all_prefix_occur = 0;
+    ds.all_suffix_occur = 0;
+    ds.all_proteins_count = 0;
```
Comment (cbielow) [inline src/openms/include/OpenMS/DATASTRUCTURES/FASTAContainer.h]: improvement:
initialize the integer members in the struct with ` = 0` directly.
Then this manual initialization here becomes unnecessary and (more importantly) this would be need for EVERY instanciation of a `DecoyStatistics`. Thus, if forgotten, it would result in weird counts.
